# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='creator',
            new_name='profile',
        ),
    ]
