# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gram', '0004_auto_20180302_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Gram.Profile')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_posted'],
            },
        ),
    ]
