# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 21:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Gram', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
