# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gram', '0006_auto_20180304_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='creator',
        ),
    ]
