# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gram', '0008_auto_20180304_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
